version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_NAME=${VITE_APP_NAME:-Autocontrol Sanitario Pro}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    restart: unless-stopped
    
  # Si tienes un backend, puedes añadirlo aquí
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=${DATABASE_URL}
  #   restart: unless-stopped